# Generated by Django 2.0.1 on 2018-02-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_availability_competence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.FloatField(default=0, verbose_name='Years of experience')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='core.Applicant')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.Competence')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='competenceprofile',
            unique_together={('applicant', 'competence')},
        ),
    ]
