# Generated by Django 2.0.1 on 2018-02-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180222_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
    ]
